"""add song_public_id and thumbnail_public_id

Revision ID: abd13a9e70ac
Revises: b7f2c9a41d38
Create Date: 2026-09-07 19:11:59.259698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd13a9e70ac'
down_revision: Union[str, None] = 'b7f2c9a41d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_public_id', sa.String(length=255), nullable=True))
    op.add_column('songs', sa.Column('thumbnail_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'thumbnail_public_id')
    op.drop_column('songs', 'song_public_id')
    # ### end Alembic commands ###
